packages:
- '.'
- submodules/gl-pal
- submodules/bullet-mini
- submodules/vr-pal
- submodules/glfw-pal
- submodules/halive
- submodules/animation-pal
- submodules/linear-extra
- submodules/lens-extra
- submodules/openvr-hs
- submodules/pd-hs
- submodules/freetype-gl-mini
- submodules/text-gl
- submodules/extensible-ecs
resolver: lts-8.5
extra-deps:
- gl-0.8.0
