resolver: nightly-2016-01-10
packages:
- '.'
- ../gl-pal
- ../udp-pal
- ../bullet-mini
- ../vr-pal
- ../glfw-pal
- ../pd-haskell
- ../halive
- ../animation-pal
- ../linear-extra
- ../lens-extra
- ../openvr-hs
- ../bindings-GLFW
- ../freetype-gl-mini
- ../tinyrick
