packages:
- '.'
- ../gl-pal
- ../bullet-mini
- ../vr-pal
- ../glfw-pal
- ../halive
- ../animation-pal
- ../linear-extra
- ../lens-extra
- ../openvr-hs
- ../pd-hs
- ../freetype-gl-mini
- ../text-gl
- ../extensible-ecs
resolver: nightly-2016-08-17
