resolver: nightly-2016-02-02
packages:
- '.'
- ../gl-pal
- ../bullet-mini
- ../vr-pal
- ../glfw-pal
- ../halive
- ../animation-pal
- ../linear-extra
- ../lens-extra
- ../openvr-hs
- ../pd-hs
- ../bindings-GLFW
- ../freetype-gl-mini
- ../text-gl
- ../extensible-ecs
